install: 
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    && sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
    && sudo apt-get update -qq
    && sudo apt-get install libmysqlcppconn-dev libsqlite3-dev g++-4.8 qt-sdk qtdeclarative5-dev
    && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
    && wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
    && tar -xzvf cmake-2.8.12.2.tar.gz
    && cd cmake-2.8.12.2
    && cmake .
    && make -j2 
    && sudo make install
    && sudo update-alternatives --install /usr/bin/cmake cmake `pwd`/bin/cmake 50
    && cd ..

language: cpp

compiler: g++

script : g++ -v
    && cd Patcher
    && cmake .
    && make
